// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for your platform - '
      'you can reconfigure this by running the FlutterFire CLI again.',
    );
  }
}

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB46DNCE5i1xuCwpDk8LScBmWZx5TlOvVE',
    appId: '1:159192741145:web:0cc0f9610b1661976f0188',
    messagingSenderId: '159192741145',
    projectId: 'chefaa-495509',
    authDomain: 'chefaa-495509.firebaseapp.com',
    storageBucket: 'chefaa-495509.firebasestorage.app',
    measurementId: 'G-19VGMQPTLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs8-b-XGUImQp9romWo86ELh2DAhPX5ZU',
    appId: '1:159192741145:android:cda5faa7cfb48e1f6f0188',
    messagingSenderId: '159192741145',
    projectId: 'chefaa-495509',
    storageBucket: 'chefaa-495509.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTqZdjqlqy42BrAmBiWe4DUl8f9Dsxw0k',
    appId: '1:159192741145:ios:fcb446d243f5d9f96f0188',
    messagingSenderId: '159192741145',
    projectId: 'chefaa-495509',
    storageBucket: 'chefaa-495509.firebasestorage.app',
    androidClientId: '159192741145-7bg65uk7ihegmrtq36v8ibpq4j8eaagb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chefaa',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTqZdjqlqy42BrAmBiWe4DUl8f9Dsxw0k',
    appId: '1:159192741145:ios:fcb446d243f5d9f96f0188',
    messagingSenderId: '159192741145',
    projectId: 'chefaa-495509',
    storageBucket: 'chefaa-495509.firebasestorage.app',
    androidClientId: '159192741145-7bg65uk7ihegmrtq36v8ibpq4j8eaagb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chefaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB46DNCE5i1xuCwpDk8LScBmWZx5TlOvVE',
    appId: '1:159192741145:web:315eee7c9e9058fd6f0188',
    messagingSenderId: '159192741145',
    projectId: 'chefaa-495509',
    authDomain: 'chefaa-495509.firebaseapp.com',
    storageBucket: 'chefaa-495509.firebasestorage.app',
    measurementId: 'G-1P73Z8Q8KL',
  );
}
