// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB66dswJasZYfEAB90pTX0zbwPK4ja2kM',
    appId: '1:50620876414:android:d49b535002d017665dfa2f',
    messagingSenderId: '50620876414',
    projectId: 'chifaa-faa5f',
    storageBucket: 'chifaa-faa5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB66dswJasZYfEAB90pTX0zbwPK4ja2kM',
    appId: '1:50620876414:ios:xxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '50620876414',
    projectId: 'chifaa-faa5f',
    storageBucket: 'chifaa-faa5f.firebasestorage.app',
    iosBundleId: 'com.example.chefaa',
  );
}
